const englishBibleBooks = {
  Genesis: {name: 'Genesis', chapters: 50},
  Exodus: {name: 'Exodus', chapters: 40},
  Leviticus: {name: 'Leviticus', chapters: 27},
  Numbers: {name: 'Numbers', chapters: 36},
  Deuteronomy: {name: 'Deuteronomy', chapters: 34},
  Joshua: {name: 'Joshua', chapters: 24},
  Judges: {name: 'Judges', chapters: 21},
  Ruth: {name: 'Ruth', chapters: 4},
  Samuel1: {name: '1 Samuel', chapters: 31},
  Samuel2: {name: '2 Samuel', chapters: 24},
  Kings1: {name: '1 Kings', chapters: 22},
  Kings2: {name: '2 Kings', chapters: 25},
  Chronicles1: {name: '1 Chronicles', chapters: 29},
  Chronicles2: {name: '2 Chronicles', chapters: 36},
  Ezra: {name: 'Ezra', chapters: 10},
  Nehemiah: {name: 'Nehemiah', chapters: 13},
  Esther: {name: 'Esther', chapters: 10},
  Job: {name: 'Job', chapters: 42},
  Psalms: {name: 'Psalms', chapters: 150},
  Proverbs: {name: 'Proverbs', chapters: 31},
  Ecclesiastes: {name: 'Ecclesiastes', chapters: 12},
  SongOfSolomon: {name: 'Song of Solomon', chapters: 8},
  Isaiah: {name: 'Isaiah', chapters: 66},
  Jeremiah: {name: 'Jeremiah', chapters: 52},
  Lamentations: {name: 'Lamentations', chapters: 5},
  Ezekiel: {name: 'Ezekiel', chapters: 48},
  Daniel: {name: 'Daniel', chapters: 12},
  Hosea: {name: 'Hosea', chapters: 14},
  Joel: {name: 'Joel', chapters: 3},
  Amos: {name: 'Amos', chapters: 9},
  Obadiah: {name: 'Obadiah', chapters: 1},
  Jonah: {name: 'Jonah', chapters: 4},
  Micah: {name: 'Micah', chapters: 7},
  Nahum: {name: 'Nahum', chapters: 3},
  Habakkuk: {name: 'Habakkuk', chapters: 3},
  Zephaniah: {name: 'Zephaniah', chapters: 3},
  Haggai: {name: 'Haggai', chapters: 2},
  Zechariah: {name: 'Zechariah', chapters: 14},
  Malachi: {name: 'Malachi', chapters: 4},
  Matthew: {name: 'Matthew', chapters: 28},
  Mark: {name: 'Mark', chapters: 16},
  Luke: {name: 'Luke', chapters: 24},
  John: {name: 'John', chapters: 21},
  Acts: {name: 'Acts', chapters: 28},
  Romans: {name: 'Romans', chapters: 16},
  Corinthians1: {name: '1 Corinthians', chapters: 16},
  Corinthians2: {name: '2 Corinthians', chapters: 13},
  Galatians: {name: 'Galatians', chapters: 6},
  Ephesians: {name: 'Ephesians', chapters: 6},
  Philippians: {name: 'Philippians', chapters: 4},
  Colossians: {name: 'Colossians', chapters: 4},
  Thessalonians1: {name: '1 Thessalonians', chapters: 5},
  Thessalonians2: {name: '2 Thessalonians', chapters: 3},
  Timothy1: {name: '1 Timothy', chapters: 6},
  Timothy2: {name: '2 Timothy', chapters: 4},
  Titus: {name: 'Titus', chapters: 3},
  Philemon: {name: 'Philemon', chapters: 1},
  Hebrews: {name: 'Hebrews', chapters: 13},
  James: {name: 'James', chapters: 5},
  Peter1: {name: '1 Peter', chapters: 5},
  Peter2: {name: '2 Peter', chapters: 3},
  John1: {name: '1 John', chapters: 5},
  John2: {name: '2 John', chapters: 1},
  John3: {name: '3 John', chapters: 1},
  Jude: {name: 'Jude', chapters: 1},
  Revelation: {name: 'Revelation', chapters: 22},
};

export default englishBibleBooks;
